server:
  port: 8080
spring:
  application:
    name: "atencionPokemon"
  devtools:
    add-properties: false
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb://localhost:27017/test"
